# This workflow periodically makes calls to the COHD API to verify it's operating as expected
name: COHD API Monitoring Workflow

on:
  # Run this workflow on a push to verify that the tests themselves are working properly
  push:
  # Schedule this workflow to run twice a day (at 0300 and 1500 UTC)
  schedule:
    - cron: '0 3/12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas
    - name: Test with pytest
      # Run the test_cohd_io.py script which makes API calls to cohd.io
      run: |
        python -m test_cohd_io
