# This workflow periodically makes calls to the COHD API to verify it's operating as expected
name: COHD API Monitoring Workflow

on:
  # Run this workflow when new code is pushed to the repo
  push:
  # Schedule this workflow to run twice a day (at 0300 and 1500 UTC)
  schedule:
    - cron: '0 3/12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas matplotlib reasoner-validator==0.9.2.*
    - name: Test cohd.io
      # Test cohd.io by running pytest on test_cohd_io.py
      # pytest -s disables pytest from capturing print statements (i.e., print statements will appear in console)
      run: |
        pip install pytest
        pytest -s test_cohd_io.py
